### PR TITLE
axis driver for ros2 humble

### PR DESCRIPTION
**Pull request by qpicard**
This AXIS ROS2 Humble driver is based on the ROS1 noetic driver.
Fully written in Python, this driver is under active development.
The implemented services are still under tests to control parameters such as focus.
The camera used is the AXIS Q1798-LE.

### CODE REVIEW

**Comment by civerachb-cpr** [comment]
I've just created a new `humble-devel` branch and changed the target branch to that.

I've also marked this as a draft for now since it looks like you're still making changes?  Please let me know when you're done and I'll review your changes

**Comment by qpicard** [comment]
Hi, 
I've made all the necessary modifications. You can review my changes.

**Comment by AiVerisimilitude** [comment]
@qpicard I have started using this PR. One suggestion would be to use default parameters for parameters whose empty values are acceptable values, for example: username, password, use_encrypted_password, camera, etc. 

I see that you set some default values on axis_camera.py #219 but not all.

**Comment by ghost** [comment]
@qpicard I am reviewing your PR.  Are there any new changes?

**Comment by civerachb-cpr** [comment]
@qpicard it look like your MR has removed all of the PTZ controls from the driver. Are you working on re-implementing these features at all?

My colleague @mhosmar-cpr has made a few changes to your MR to clean up the code a little, but we're both wondering why you seem to have removed the ability to actually control the cameras' pan & tilt, as well as the ability to zoom the camera in and out.

**Comment by qpicard** [comment]
@civerachb-cpr @mhosmar-cpr I am not working on re-implementing the PTZ controls.
I can't remember why I removed them. 
Unfortunately, I can no longer work on this project.
I let you decide what to do with the current state of the code.
You can either do the work to implement the PTZ controls or let someone else do it...
I still think that the current project is useful for many people working on ROS2 with the AXIS cameras.

Thanks,

Quentin

**Comment by civerachb-cpr** [comment]
Thanks for letting us know. As you've probably noticed, we've already been making a few changes to your merge request to tidy things up and revert some unnecessary changes.  We'll probably be merging this soon and then getting to work adding the remaining features.

**Pull request merged**
